### ISSUE TITLE
Create docker container

### ISSUE THREAD

**Issue by ingenieroariel** [piensa/sdc-steering#1]
That has:
- [x] Keras 
- [x] Tensorflow
- [x] ROS
- [x] Jupyter
- [ ] cuDNN
- [ ] Both CPU and GPU version of the docker machine

**Comment by JorgeMrtnzG** [comment]
https://hub.docker.com/r/kaixhin/cuda-theano/~/dockerfile/

**Comment by ingenieroariel** [comment]
Waiting for build ... I'll focus on the non GPU version first so we can get going.

**Comment by ingenieroariel** [comment]
https://hub.docker.com/r/piensa/deeplearning/builds/

**Comment by ingenieroariel** [comment]
https://github.com/piensa/dl-docker

**Comment by ingenieroariel** [comment]
Once we have the docker base image we should be able to avoid building it all the time. I'll create a docker-compose.yml and docker-compose.override.yml for this repo.

**Comment by ingenieroariel** [comment]
This can be closed now - the container is `piensa/deeplearning` on docker hub.

GPU stuff tracked here: https://github.com/piensa/sdc-steering/issues/4
