### ISSUE TITLE
Error with array's shape! on cnn.py

### ISSUE THREAD

**Issue by waybarrios** [piensa/sdc-steering#3]
```
ipdb> c
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
/home/wbarrios/code/sdc-steering/steering/cnn.py in <module>()
     72 
     73 # 5. ConvLayer: 3x3 kernel, 48 kernels, no stride.
---> 74 model.add(Convolution2D(48, 3, 3,
     75                         border_mode='same'))
     76 

```

`Exception: Error when checking model target: expected activation_1 to have shape (None, 5) but got array with shape (10000, 10)`

**Comment by ingenieroariel** [comment]
@waybarrios how did you find it out? what command did you run?

**Comment by waybarrios** [comment]
@ingenieroariel  I'm on it! I tested our networks with cifar10. It means it problems with shape due to matrix size between layers! When I have the dataset, I will retrain it! I just ran `python cnn.py`with ipdb

**Comment by ingenieroariel** [comment]
@waybarrios you can use the sample.bag data in `/data/data/sample.bag` in the container. It has just like 8 images but should be enough to train  dummy network and set the sizes right.

**Comment by ingenieroariel** [comment]
it's based on https://hub.docker.com/r/piensa/sdcdata/builds/
